### ISSUE TITLE
Add variable option for handbrake version

### ISSUE THREAD

**Issue by luigi311** [jlesage/docker-templates#1]
On your handbrake template can you add the ability to set the variable for HANDBRAKE_VERSION so it can be passed through to the build script. This would help people change the handbrake version via the webgui on unraid easily when new version arrive without you having to manually update the option.

**Comment by jlesage** [comment]
Not sure if I understand your point correctly, put there is no relation between a container environment variable and the build process.

Variables defined in the unRAID template are used for the creation of the container (`-p` parameter of the `docker run` command).  These variables are then available for applications/processes running in the container.

The `HANDBRAKE_VERSION` variable used in the Dockerfile is used only to build the image.

From what I understand, what you want to achieve would requires to have 2 different HandBrake binaries in the image of have two separate images.

**Comment by luigi311** [comment]
Ohh wait your right. Unraid just downloads the image that you created and posted on docker hub not sure why I thought it used the dockerfile to build the image.

**Comment by jlesage** [comment]
Ok no problem, case closed :)
